### ISSUE TITLE
Class 'Kofikwarteng\LaravelSagepay\SagePayServiceProvider' not found

### ISSUE THREAD

**Issue by trocho** [kofispaceman/laravel-sagepay#2]
Hi.

You have a small mistake which occurs on a linux in the Service Provider name at manual. 'Pay' should be lowercase - SagepayServiceProvider not SagePayServiceProvider.

**Comment by kofi1995** [comment]
Thanks for pointing out the issue. I will take a look at it. I'm quite busy so can you create a pull request and correct it so I commit the change?

**Comment by kofi1995** [comment]
I have solved it in the latest release. Thanks.
