### ISSUE TITLE
Errors with $this->app->share

### ISSUE THREAD

**Issue by Steven-Robinson** [kofispaceman/laravel-sagepay#4]
This is broken in the latest version of Laravel. Errors on $this->app->share as the share method has been removed:

`local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::share()' in [PATH]/vendor/kofikwarteng/laravel-sagepay/src/SagePayServiceProvider.php:33`

Have tried replacing share with singleton but then errors with `'ErrorException' with message 'Illegal offset type in unset' in [PATH]/vendor/laravel/framework/src/Illuminate/Container/Container.php:988`

**Comment by kofi1995** [comment]
Sorry, @Steven-Robinson I've been quite busy. Create a pull request, correct the code and I'll gladly merge the change, thanks.

**Comment by kofi1995** [comment]
Thanks once again for your contribution.
